# Generated by Django 3.1.3 on 2020-11-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('id_install', models.IntegerField(verbose_name='id_install')),
                ('result_work', models.BooleanField(default=False, verbose_name='result_work')),
            ],
        ),
    ]
