# Generated by Django 3.1.3 on 2020-11-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultWorkForTaskManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_install', models.IntegerField(verbose_name='id_install')),
                ('result_work', models.BooleanField(default=False, verbose_name='result_work')),
            ],
        ),
        migrations.RemoveField(
            model_name='resultwork',
            name='date',
        ),
        migrations.AddField(
            model_name='resultwork',
            name='computer_name',
            field=models.CharField(default='none_name', max_length=32, verbose_name='computer_name'),
        ),
        migrations.AddField(
            model_name='resultwork',
            name='events_id',
            field=models.IntegerField(default=10, verbose_name='events_id'),
        ),
        migrations.AddField(
            model_name='resultwork',
            name='program_name',
            field=models.CharField(default='none_name', max_length=32, verbose_name='program_name'),
        ),
    ]
