# Generated by Django 3.1.3 on 2020-12-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20201125_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultwork',
            name='status_code',
            field=models.BooleanField(default=False, verbose_name='status_code'),
        ),
    ]
