# Generated by Django 3.1.3 on 2020-12-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_resultwork_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultwork',
            name='program_id',
            field=models.IntegerField(default=0, verbose_name='program_id'),
        ),
    ]
