# Generated by Django 3.1.4 on 2020-12-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_resultwork_program_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultwork',
            name='distinguished_name',
            field=models.CharField(default='none', max_length=200, verbose_name='distinguished_name'),
        ),
    ]
