version: '3.7'

services:
  web:
    build: ./Backendproject
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backendproject:/usr/src/app
      - ./scriptsForClient:/usr/src/scripts
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db


  celery:
    build: ./Backendproject
    command: celery worker --app=PM --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./Backendproject:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  dashboard:
    build: ./Backendproject
    command:  flower -A PM --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - celery


  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db_logs12
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./my-db:/var/lib/mysql



  redis:
    image: redis:5-alpine

  djangoforclientapp:
    build: ./djangoForClientApp
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./djangoForClientApp:/usr/src/app
      - ./scriptsForClient:/usr/src/scripts
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0


  nginx:
    build: ./nginx
    command: nginx
    volumes:
      - ./softDistributes:/usr/src/dicstributes
      - ./scriptsForClient:/usr/src/scripts
    ports:
        - 8081:80
    depends_on:
        - web
        - djangoforclientapp
