version: '3.7'

services:
  main-server:
    build: pm_main_server
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pm_main_server:/usr/src/app
      - ./scriptsForClient:/usr/src/scripts
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db-main


  celery:
    build: pm_main_server
    command: celery worker --app=main_server --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./pm_main_server:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - main-server
      - redis

  dashboard-celery:
    build: pm_main_server
    command:  flower -A main_server --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - main-server
      - redis
      - celery


  db-main:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: db_logs12
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./my-db:/var/lib/mysql



  redis:
    image: redis:5-alpine

  functional-server:
    build: pm_functional_server
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pm_functional_server:/usr/src/app
      - ./scriptsForClient:/usr/src/scripts
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0


  nginx:
    build: ./nginx
    command: nginx
    volumes:
      - ./softDistributes:/usr/src/dicstributes
      - ./scriptsForClient:/usr/src/scripts
    ports:
        - 8081:80
    depends_on:
        - main-server
        - functional-server
