# Generated by Django 3.1.3 on 2020-11-21 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc_name', models.CharField(max_length=128, verbose_name='proc_name')),
                ('short_program_name', models.CharField(max_length=128, verbose_name='short_program_name')),
                ('proc_description', models.CharField(max_length=128, verbose_name='proc_description')),
                ('program_name', models.CharField(max_length=128, verbose_name='program_name')),
                ('program_file', models.CharField(max_length=128, verbose_name='program_file')),
                ('key_string', models.CharField(max_length=128, verbose_name='key_string')),
                ('zip', models.BooleanField(verbose_name='zip')),
                ('archive', models.CharField(max_length=128, verbose_name='archive')),
                ('distribute_name', models.CharField(max_length=128, verbose_name='distribute_name')),
                ('program_shortcut', models.CharField(max_length=128, verbose_name='program_shortcut')),
                ('drive_letter', models.CharField(max_length=128, verbose_name='drive_letter')),
                ('path_to_setup', models.CharField(max_length=128, verbose_name='path_to_setup')),
            ],
        ),
        migrations.CreateModel(
            name='LogsInstallationSoft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('id_install', models.IntegerField(verbose_name='id_install')),
                ('startnumber', models.IntegerField(verbose_name='startnumber')),
                ('computer_name', models.CharField(max_length=32, verbose_name='computer_name')),
                ('events_id', models.IntegerField(choices=[(1, 'finded in AD'), (2, 'NOT finded in AD'), (3, 'have in computer'), (4, 'soft installed'), (5, 'work completed')], verbose_name='events_id')),
                ('result_work', models.BooleanField(default=False, verbose_name='result_work')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_construction.soft', verbose_name='program_id')),
            ],
        ),
    ]
